= geekbang-lessons
:toc: macro
:toclevels: 4
:icons: font
:source-highlighter: rouge

极客时间课程工程

.打包
[source,bash]
----
mvn -f projects/stage-0/user-platform/pom.xml clean package -U
----

.运行
[source,bash]
----
java -jar projects/stage-0/user-platform/user-web/target/user-web-v1-SNAPSHOT-war-exec.jar
----

'''

toc::[]

'''

== 第四周作业

[quote,作业要求]
____
. 完善 my dependency-injection 模块
* 脱离 web.xml 配置实现 ComponentContext 自动初始化
* 使用独立模块并且能够在 user-web 中运行成功
. 完善 my-configuration 模块
* Config 对象如何能被 my-web-mvc 使用
* 可能在 ServletContext 获取如何通过 ThreadLocal 获取
. 去提前阅读 Servlet 规范中 Security 章节（Servlet 容器安全）
____

=== my-dependency-injection

[.lead]
脱离 web.xml 配置实现 ComponentContext 自动初始化

==== 自定义 `ServletContextListener`

link:projects/stage-0/user-platform/my-dependency-injection/src/main/java/org/geektimes/config/ComponentContextListener.java[org.geektimes.config.ComponentContextListener]

[source,java]
----
@Override
public void contextInitialized(ServletContextEvent sce) {
  ServletContext ctx = sce.getServletContext();
  ClassicComponentContext componentContext = new ClassicComponentContext();
  componentContext.init(ctx);
}
----

==== 添加自定义 `ServletContextListener`

link:projects/stage-0/user-platform/my-dependency-injection/src/main/java/org/geektimes/config/ComponentContainerInitializer.java[org.geektimes.config.ComponentContainerInitializer]

[source,java]
----
@Override
public void onStartup(Set<Class<?>> c, ServletContext ctx) throws ServletException {
  ctx.addListener(ComponentContextListener.class);
}
----

==== 配置 SPI

link:projects/stage-0/user-platform/my-dependency-injection/src/main/resources/META-INF/services/javax.servlet.ServletContainerInitializer[javax.servlet.ServletContainerInitializer]

----
org.geektimes.config.ComponentContainerInitializer
----

==== 在 `user-web` 中验证

. 注释掉 link:projects/stage-0/user-platform/user-web/src/main/webapp/WEB-INF/web.xml[web.xml] 中的 listener

. link:projects/stage-0/user-platform/user-web/src/main/java/org/geektimes/projects/user/web/controller/HelloWorldController.java[HelloWorldController] 中调用 `ClassicComponentContext` 方法
+
[source,java]
----
ClassicComponentContext instance = ClassicComponentContext.getInstance();
List<String> componentNames = instance.getComponentNames();
System.out.println("ComponentContext componentNames:");
System.out.println(componentNames);
----

. 启动应用, 浏览器访问 `http://localhost:8080/hello/world`
+
.控制台返回注入信息, 成功
----
ComponentContext componentNames:
[maxValue, jdbc/UserPlatformDB, bean/EntityManager, bean/UserService, bean/DBConnectionManager, bean/Validator]
----
